<?php 
require_once("models/message.inc");

function message_center_init(){
	define("MESSAGE_CENTER_ROOT_PATH",drupal_get_path('module', 'message_center'));
}

/**
 * Implementation of hook_perm().
 */
function message_center_permission() {
	return array(
			"create messages"	=> array('title' => "Can Create Messages"),
			"edit messages"		=> array('title' => "Can Edit Messages"),
			"delete messages"	=> array('title' => "Can Delete Messages"),
			"view messages"		=> array('title' => "Can View Messages"),
	);
}

function message_center_check_permission($permission){
	global $user;
	return user_access($permission, $user);
}

function message_center_menu() {
	$items['admin/message_center/edit/%'] = array(
			'title'	=> 'Edit Message',
			'description' => "Edit a Message Center Message",
			'page arguments' => array(3),
			'page callback' => 'message_center_edit_message',
			'file' => 'message_center.admin.inc',
			'access callback' => 'message_center_check_permission',
			'access arguments' => array('edit messages')
	);

	return $items;
}


/**
 * Implements hook_block_info().
 */
function message_center_block_info() {
	$blocks['message_center'] = array(
			'info' => t('Message Center'), //The name that will appear in the block list.
			'cache' => DRUPAL_NO_CACHE // DRUPAL_CACHE_PER_ROLE, //Default
	);
	return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function message_center_block_view($delta = '') {
	switch($delta){
		case 'message_center':
			$block['subject'] = t('Message Center');
			$view = new StdClass();
			$view->messages = message::search()
				->order('created_date', 'DESC')
				->exec();
			$block['content'] = message_center_template_view(MESSAGE_CENTER_ROOT_PATH . "/templates/message_center.phtml", $view);
			return $block;
	}
}

/**
 * Crunch through a view
 * @param string $file File of the template to call.
 * @param array|object $view Optional view array.
 * @return string
 */
function message_center_template_view($file, $view = null){
	$file = DRUPAL_ROOT . "/" . $file;
	if(!file_exists($file)){
		return "Cannot find {$file}";
	}
	extract((array) $view);
	ob_start();
	require($file);
	$markup = ob_get_contents();
	ob_end_clean();
	return $markup;
}
