<?php 
require_once("models/message.inc");

function message_centre_init(){
	define("MESSAGE_CENTRE_ROOT_PATH",drupal_get_path('module', 'message_centre'));
}

/**
 * Implementation of hook_perm().
 */
function message_centre_permission() {
	return array(
			"create messages"	=> array('title' => "Can Create Messages"),
			"edit messages"		=> array('title' => "Can Edit Messages"),
			"delete messages"	=> array('title' => "Can Delete Messages"),
			"view messages"		=> array('title' => "Can View Messages"),
	);
}

function message_centre_check_permission($permission){
	global $user;
	return user_access($permission, $user);
}

function message_centre_menu() {
	$items['admin/message_centre/delete/%'] = array(
			'title'	=> 'Delete Message',
			'description' => "Delete a Message Centre Message",
			'page arguments' => array(3),
			'page callback' => 'message_centre_delete_message',
			'file' => 'message_centre.admin.inc',
			'access callback' => 'message_centre_check_permission',
			'access arguments' => array('delete messages')
	);
	
	$items['admin/message_centre/edit/%'] = array(
			'title'	=> 'Edit Message',
			'description' => "Edit a Message Centre Message",
			'page arguments' => array(3),
			'page callback' => 'message_centre_edit_message',
			'file' => 'message_centre.admin.inc',
			'access callback' => 'message_centre_check_permission',
			'access arguments' => array('edit messages')
	);
	
	$items['admin/message_centre/add'] = array(
			'title'	=> 'Add new Message',
			'description' => "Add a new Message Centre Message",
			'page callback' => 'message_centre_add_message',
			'file' => 'message_centre.admin.inc',
			'access callback' => 'message_centre_check_permission',
			'access arguments' => array('create messages')
	);

	return $items;
}


/**
 * Implements hook_block_info().
 */
function message_centre_block_info() {
	$blocks['message_centre'] = array(
			'info' => t('Message Centre'), //The name that will appear in the block list.
			'cache' => DRUPAL_NO_CACHE // DRUPAL_CACHE_PER_ROLE, //Default
	);
	return $blocks;
}

/**
 * Implements hook_block_view().
 *
 * Prepares the contents of the block.
 */
function message_centre_block_view($delta = '') {
	switch($delta){
		case 'message_centre':
			$block['subject'] = t('Message Centre');
			$view = new StdClass();
			$view->messages = message::search()
				->order('created_date', 'DESC')
				->where('message_heading','New Message', '!=')
				->where('message_body','', '!=')
				->exec();
			$block['content'] = message_centre_template_view(MESSAGE_CENTRE_ROOT_PATH . "/templates/message_centre.phtml", $view);
			return $block;
	}
}

/**
 * Crunch through a view
 * @param string $file File of the template to call.
 * @param array|object $view Optional view array.
 * @return string
 */
function message_centre_template_view($file, $view = null){
	$file = DRUPAL_ROOT . "/" . $file;
	if(!file_exists($file)){
		return "Cannot find {$file}";
	}
	extract((array) $view);
	ob_start();
	require($file);
	$markup = ob_get_contents();
	ob_end_clean();
	return $markup;
}
