<h3><?=t('Message "<em>@message_geading</em>"', array('@message_geading' => $message->message_heading)); ?> </h3>

<form method="post" action="" class="message_edit">
  <?php if (isset($_SERVER['HTTP_REFERER'])): ?>
    <input name="dest" type="hidden" value="<?=$_SERVER['HTTP_REFERER']?>"/>
  <?php endif; ?>
    <fieldset>
        <legend><?=t("@create_or_edit message",array('@create_or_edit' => ucfirst($create_or_edit)));?>: </legend>
        <div class="fieldset-wrapper">

            <div class="form-item form-type-textfield">
                <label><?=t("Message Heading")?></label>
                <input class="form-text" type="text" name="message_heading" value="<?=$message->message_heading?>"/>
            </div>

            <div class="form-item form-type-textarea resizable">
                <label><?=t("Message Body")?></label>

                <div class="form-textarea-wrapper resizable textarea-processed resizable-textarea">
                    <textarea class="form-textarea" name="message_body" cols="60" rows="20"><?=$message->message_body?></textarea>
                    <div class="grippie"></div>
                </div>
            </div>

            <div class="form-item form-type-radios">
                <label><?=t("Mark as Sticky?")?></label>
                <div class="form-radios">
                    <div class="form-item form-type-radio">
                        <input class="form-radio" type="radio" name="sticky" value="Yes" id="sticky_yes" <?=$message->is_sticky()?'checked="checked"':''?>>
                        <label class="option" for="sticky_yes"><?=t("Yes")?></label><br/>
                    </div>
                    <div class="form-item form-type-radio">
                        <input class="form-radio" type="radio" name="sticky" value="No" id="sticky_no"  <?=!$message->is_sticky()?'checked="checked"':''?>>
                        <label class="option" for="sticky_no"><?=t("No")?></label>
                    </div>
                </div>
            </div>

        </div>
    </fieldset>
    <div class="form-actions" id="edit-actions">
        <input type="submit" id="edit-submit" name="op" value="<?=t("Save Message")?>" class="form-submit">
    </div>
</form>
