<div class="message <?=user_access('create messages')||user_access('edit messages')||user_access('delete messages')?'editor':'viewer'?>">
	<div class="main">
		<div class="heading">
			<div class="icon"></div>
			<h3>
				<?php echo $message->message_heading; ?>
			</h3>
		</div>
		<div class="body">
			<?php echo $message->message_body; ?>
		</div>
		<div class="author">
			<?=t(
					"Written by <b>@author</b> at <b>@time</b>", 
					array(
						'@author' => $message->get_created_user()->name, 
						'@time' => date("l jS \of F Y h:i:s A", strtotime($message->created_date))
					)
				);?>
		</div>
	</div>
	<?php if(user_access('edit messages')||user_access('delete messages')?'editor':'viewer'):?>
		<div class="options">
			<ul class="buttons">
				<?php if(user_access('edit messages')):?>
				<li class="message-edit" title="<?=t("Edit Message");?>">
					<a href="admin/message_center/edit/<?=$message->get_slug()?>">
						<span><?=t("Edit Message")?></span>
					</a>
				</li>
				<?php endif; ?>

				<?php if(user_access('delete messages')):?>
				<li class="message-delete" title="<?=t("Delete Message");?>">
					<a href="admin/message_center/delete/<?=$message->get_slug()?>">
						<span><?=t("Delete Message")?></span>
					</a>
				</li>
				<?php endif; ?>
			</ul>
		</div>
	<?php endif;?>
</div>